baseImageOverrides:
  github.com/kyma-project/test-infra/cmd/image-autobumper: europe-docker.pkg.dev/kyma-project/prod/testimages/alpine-git:v20240705-f43bf98f
defaultPlatforms:
  - linux/arm64
  - linux/amd64
