name: pull-build-automated-approver
on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    paths:
      - "cmd/external-plugins/automated-approver/*.go"
      - "cmd/external-plugins/automated-approver/Dockerfile"
      - "pkg/**"
      - "go.mod"
      - "go.sum"

jobs:
  build-image:
    uses: ./.github/workflows/image-builder.yml
    with:
      name: automated-approver
      dockerfile: cmd/external-plugins/automated-approver/Dockerfile
      context: .
  print-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Print image
        run: echo "Image built ${{ needs.build-image.outputs.images }}"
