name: pull-build-github-webhook-gateway
on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    paths:
      - "cmd/cloud-run/github-webhook-gateway/*.go"
      - "cmd/cloud-run/github-webhook-gateway/Dockerfile"
      - "pkg/**"
      - "go.mod"
      - "go.sum"

jobs:
  build-image:
    uses: ./.github/workflows/image-builder.yml
    with:
      name: github-webhook-gateway
      dockerfile: cmd/cloud-run/github-webhook-gateway/Dockerfile
      context: .
  print-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Print image
        run: echo "Image built ${{ needs.build-image.outputs.images }}"
