name: pull-build-pjtester
on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    paths:
      - "cmd/tools/pjtester/*.go"
      - "cmd/tools/pjtester/Dockerfile"
      - "pkg/**"
      - "go.mod"
      - "go.sum"

jobs:
  build-image:
    uses: ./.github/workflows/image-builder.yml
    with:
      name: pjtester
      dockerfile: cmd/tools/pjtester/Dockerfile
      context: .
  print-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Print image
        run: echo "Image built ${{ needs.build-image.outputs.images }}"
