name: push-build-search-github-issue
on:
  push:
    branches:
      - main
    paths:
      - "cmd/cloud-run/search-github-issue/*.go"
      - "cmd/cloud-run/search-github-issue/Dockerfile"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
  workflow_dispatch: {}

jobs:
  build-image:
    uses: ./.github/workflows/image-builder.yml
    with:
      name: search-github-issue
      dockerfile: cmd/cloud-run/search-github-issue/Dockerfile
      context: .
  print-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Print image
        run: echo "Image built ${{ needs.build-image.outputs.images }}"
