name: push-build-image-url-helper
on:
  push:
    branches:
      - main
    paths:
      - "cmd/image-url-helper/*.go"
      - "cmd/image-url-helper/Dockerfile"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
  workflow_dispatch: {}

jobs:
  build-image:
    uses: ./.github/workflows/image-builder.yml
    with:
      name: image-url-helper
      dockerfile: cmd/image-url-helper/Dockerfile
      context: .
  print-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Print image
        run: echo "Image built ${{ needs.build-image.outputs.images }}"
